config/routes.rb
LiftClone::Application.routes.draw do

  get "/feed" => "users#index", as: :feed

  resource  :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :index] do
    resources :goals, shallow: true
  end
  root 'sessions#new'


end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :user_id, presence: true
  # validates :public, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :ensure_session_token!

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true
  has_many :goals
  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def password=(plain_text)
    @password = plain_text
    self.password_digest = BCrypt::Password.create(plain_text)
  end

  def is_password?(plain_text)
    BCrypt::Password.new(self.password_digest).is_password?(plain_text)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

    def ensure_session_token!
      self.session_token ||= SecureRandom::urlsafe_base64(16)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  helper_method :current_user, :login_user, :logged_in?, :logout, :require_user
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    render :new
  end

  def create
    @user = current_user
    @goal = Goal.new(goal_params)
    @goal.user_id = @user.id

    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def index
  end

  def destroy
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :description, :public, :completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["Wrong username or password! But which one?? HAHA!"]
      render :new
    else
      login(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def destroy
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :session_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil unless session[:session_token]
    @current_user = User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def require_user
    redirect_to new_session_url unless logged_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<% action = ( @goal.persisted? ? goal_url(@goal) : user_goals_url(current_user)  )  %>
<% method = ( @goal.persisted? ? "PATCH" 							: "POST"   )  %>
<% title =  ( @goal.persisted? ? "Edit Goal" 					: "New Goal"  )  %>
<% submit = ( @goal.persisted? ? "Update Goal" 				: "Create Goal"  )  %>

<h1><%= title %></h1>
<form action="<%= action %>" method="POST" accept-charset="utf-8">
	<input type="hidden"
				 name="authenticity_token"
				 value="<%= form_authenticity_token %>">

	<input type="hidden" name="_method" value="<%= method %>">

	<label>Goal Title
		<input type="text" name="goal[title]" value="<%= @goal.title %>">
	</label>
	<br>

	<label>Goal Description
		<textarea name="goal[description]"><%= @goal.description %></textarea>
	</label>
	<br>

  <label>Public
	  <input type="radio" name="goal[public]" value="true" <%= "checked" if @goal.public %>>
	</label>

	<label>Private
	  <input type="radio" name="goal[public]" value="false" <%= "checked" if !@goal.public %>>
  </label>
	<br>

 	<input type="submit" value="<%= submit %>">
</form>

app/views/goals/_goal.html.erb
<h1><%= goal.title %></h1>
<br>
<p><%= goal.description %></p>
<br>
<% if goal.completed %>
  <h4>Completed</h4>
<% end %>

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

app/views/goals/edit.html.erb
<%= render 'form' %>

app/views/goals/index.html.erb
<h1>Goals#index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

app/views/goals/new.html.erb
<%= render 'form' %>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>
<h3><%= @goal.description %></h1>
<p>Status: <%= @goal.completed ? "Complete" : "Incomplete" %></p>
<%= form_for @goal do |g| %>
	<%= g.hidden_field :completed, value: true %>
	<%= g.submit "Complete Goal" %>
<% end %>


<%= link_to "Edit Goal", edit_goal_url(@goal) %><br>
<%= link_to "Back to Home", user_url(@goal.user) %>

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LiftClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/errors' unless flash[:errors].nil? %>

<% if logged_in? %>
	<%= current_user.username %>
	<%= button_to "Log Out", session_url, method: :delete %>
	<br>
<% else %>
	<%= link_to "Sign In", new_session_url %>
	<%= link_to "Sign Up", new_user_url %>
	<br>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% flash[:errors].each do |error| %>
<p><%= error %></p>
<% end %>

app/views/users/_form.html.erb
<form action="<%= users_url %>" method="POST" accept-charset="utf-8">

	<input type="hidden"
				 name="authenticity_token"
				 value="<%= form_authenticity_token %>">

	<label>Username
		<input type="text" name="user[username]">
	</label>
	<br>

	<label>Password
		<input type="password" name="user[password]">
	</label>
	<br>

 	 <input type="submit" value="Sign Up">
</form>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Goals Feed</h1>

<ul>
	<% @users.each do |user| %>
	  <li>
			<strong>
				<%= user.username %>
			</strong>
		</li>
		<ol>
		  <% user.goals.each do |goal| %>
			<% if goal.public %>
			  <li>
				<strong><%= goal.title.capitalize %></strong>
				<p>Description: <%= goal.description %></p>
				<p>Status: <%= goal.completed ? "Complete" : "Incomplete" %></p><br>
				<% end %>
			  </li>
			<% end %>
		</ol>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %> Home</h1>
<%= render @user.goals %>
<%= link_to "Create New Goal", new_user_goal_url(@user) %><br>
<%= link_to "Goal Feed", feed_url %>